# Generated by Django 5.1 on 2024-09-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='own_restaurants',
        ),
    ]
