# Generated by Django 5.1 on 2024-08-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_image_alter_pizza_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoughType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough', models.CharField(db_index=True, max_length=20, verbose_name='Dough type')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pizzas.doughtype', verbose_name='Dough'),
        ),
    ]
