# Generated by Django 5.1 on 2024-08-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_drinktype_drinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.DeleteModel(
            name='DrinkType',
        ),
    ]
