# Generated by Django 5.1 on 2024-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_rename_details_b_burger_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meatroast',
            name='meat_roast_level',
            field=models.CharField(choices=[('medium', 'Medium'), ('medium_rare', 'Medium Rare'), ('rare', 'Rare'), ('well_done', 'Well Done')], max_length=50),
        ),
    ]
