# Generated by Django 5.1 on 2024-08-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_alter_meatroast_meat_roast_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('burgers', models.ManyToManyField(related_name='restaurant', to='pizzas.burger')),
                ('pizzas', models.ManyToManyField(related_name='restaurant', to='pizzas.pizza')),
            ],
        ),
    ]
