# Generated by Django 5.1 on 2024-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0009_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
