# Generated by Django 5.1 on 2024-08-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0011_restaurants_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='url',
        ),
    ]
