# Generated by Django 5.1 on 2024-08-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0012_remove_restaurants_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='burgers',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurant', to='pizzas.burger'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='pizzas',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurant', to='pizzas.pizza'),
        ),
    ]
